#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

env_opts_var=`basename $0 | sed 's/\.sh$//' | tr 'a-z-' 'A-Z_'`_OPTS
USAGE="\
   usage: `basename $0` [-z partition] [-e environment]
examples: `basename $0` -z partition_0 -e tracker

-c,--config      Config file to read
-z,--partition   Partition to set up
-e,--environment Environment to set up
-u,--update-only Do not create the test_rel if it does not exist
"
 
config_file="~/daq-shifter-tools/daq-operations.yaml"
partition="partition_0"
environment="default"
update_only=0

# Process script arguments and options
eval env_opts=\${$env_opts_var-} # can be args too

eval "set -- $env_opts \"\$@\""
op1chr='rest=`expr "$op" : "[^-]\(.*\)"`   && set -- "-$rest" "$@"'
op1arg='rest=`expr "$op" : "[^-]\(.*\)"`   && set --  "$rest" "$@"'
reqarg="$op1arg;"'test -z "${1+1}" &&echo opt -$op requires arg. &&echo "$USAGE" &&exit'
args= do_help=
while [ -n "${1-}" ];do
    if expr "x${1-}" : 'x-' >/dev/null;then
        op=`expr "x$1" : 'x-\(.*\)'`; shift   # done with $1
        leq=`expr "x$op" : 'x-[^=]*\(=\)'` lev=`expr "x$op" : 'x-[^=]*=\(.*\)'`
        test -n "$leq"&&eval "set -- \"\$lev\" \"\$@\""&&op=`expr "x$op" : 'x\([^=]*\)'`
        case "$op" in
            \?*|h*)       eval $op1chr; do_help=1;;
            c*)           eval $reqarg; config_file=$1; shift;;
            e*)           eval $reqarg; environment=$1; shift;;
            z*)           eval $reqarg; partition=$1; shift;;
            u*)           eval $op1chr; update_only=1;;
            -config)      eval $reqarg; config_file=$1; shift;;
            -partition)   eval $reqarg; partition=$1; shift;;
            -environment) eval $reqarg; environment=$1; shift;;
            -update-only) eval $op1arg; update_only=1;;
            -debug) eval op1arg; set -x;;
            *)          echo "Unknown option -$op"; do_help=1;;
        esac
    else
        aa=`echo "$1" | sed -e"s/'/'\"'\"'/g"` args="$args '$aa'"; shift
    fi
done
eval "set -- $args \"\$@\""; unset args aa

test -n "${do_help-}" -o $# -ge 2 && echo "$USAGE" && exit

dir=`SCRIPT_DIR/common/read_config.py --config $config_file --partition $partition --environment $environment directory`
if [! -d $dir ]; then
    if [ $update_only -eq 1 ];then
      echo "Directory $dir does not exist, and the script is in update-only mode!"
    else
      mkdir -p $dir
      cd $dir
      curl -O https://raw.githubusercontent.com/Mu2e/otsdaq-mu2e/refs/heads/develop/tools/mu2e-quick-spack-start.sh
      chmod +x mu2e-quick-spack-start.sh
      base_release=`$SCRIPT_DIR/common/read_config.py --config $config_file --partition $partition base_release`
      ./mu2e-quick-spack-start.sh --develop --upstream $base_release
    fi
else
  cd $dir
  ./mu2e-quick-spack-start.sh --develop
fi

