#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

env_opts_var=`basename $0 | sed 's/\.sh$//' | tr 'a-z-' 'A-Z_'`_OPTS
USAGE="\
   usage: `basename $0` [-z partition] [-e environment]
examples: `basename $0` -z partition_0 -e tracker

-c,--config      Config file to read
-z,--partition   Partition to set up
-e,--environment Environment to set up
"

# First retrieve the users krb5 credentials and set up the environment for kerb access
source get_krb_principal.sh
# Now setup the GitHub Evironment keyed off the kerberous id
source setup_git_env.sh
# At this point we should be able to access GitHub

#
# Now setup the defaults for the configuration files and partitions to use
config_file="~/daq-shifter-tools/daq-operations.yaml"
resource_file="mu2e_resource_manager.yaml"
partition="partition_0"
environment="default"

# Process script arguments and options
eval env_opts=\${$env_opts_var-} # can be args too

eval "set -- $env_opts \"\$@\""
op1chr='rest=`expr "$op" : "[^-]\(.*\)"`   && set -- "-$rest" "$@"'
op1arg='rest=`expr "$op" : "[^-]\(.*\)"`   && set --  "$rest" "$@"'
reqarg="$op1arg;"'test -z "${1+1}" &&echo opt -$op requires arg. &&echo "$USAGE" &&exit'
args= do_help=
while [ -n "${1-}" ];do
    if expr "x${1-}" : 'x-' >/dev/null;then
        op=`expr "x$1" : 'x-\(.*\)'`; shift   # done with $1
        leq=`expr "x$op" : 'x-[^=]*\(=\)'` lev=`expr "x$op" : 'x-[^=]*=\(.*\)'`
        test -n "$leq"&&eval "set -- \"\$lev\" \"\$@\""&&op=`expr "x$op" : 'x\([^=]*\)'`
        case "$op" in
            \?*|h*)       eval $op1chr; do_help=1;;
            c*)           eval $reqarg; config_file=$1; shift;;
            e*)           eval $reqarg; environment=$1; shift;;
            z*)           eval $reqarg; partition=$1; shift;;
            -config)      eval $reqarg; config_file=$1; shift;;
            -partition)   eval $reqarg; partition=$1; shift;;
            -environment) eval $reqarg; environment=$1; shift;;
            -debug) eval op1arg; set -x;;
            *)          echo "Unknown option -$op"; do_help=1;;
        esac
    else
        aa=`echo "$1" | sed -e"s/'/'\"'\"'/g"` args="$args '$aa'"; shift
    fi
done
eval "set -- $args \"\$@\""; unset args aa

test -n "${do_help-}" -o $# -ge 2 && echo "$USAGE" && exit

dir=`SCRIPT_DIR/common/read_config.py --config $config_file --partition $partition --environment $environment directory`
if [ -d $dir ]; then
  cd $dir
  source `SCRIPT_DIR/common/read_config.py --config $config_file --partition $partition --environment $environment setup`
fi
