# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

. "$HOME/.local/bin/env"

# Destroy any kerberos tickets to only use the group keytab
kdestroy
